In [1]:
import numpy as np
import pandas as pd
train= np.loadtxt("ccpptrain.csv", delimiter=",")
test=np.loadtxt("ccpptest.csv", delimiter=",")

In [2]:
df=pd.DataFrame(train[:,:4])
d=pd.DataFrame(test)

In [3]:
from sklearn import preprocessing
xscaled=preprocessing.scale(df)
test=preprocessing.scale(d)
print(xscaled)

[[ -1.47827466e+00  -1.24764165e+00   1.30221067e+00   7.58624590e-01]
 [  2.89012041e-01   3.06797549e-01   6.61749044e-01  -4.46921842e-01]
 [ -3.99975582e-01  -4.21012529e-01  -2.87207194e-01   3.75010552e-01]
 ..., 
 [  1.36062192e+00   1.18048335e+00  -6.54382840e-01  -5.83682640e-01]
 [ -4.36097263e-01   9.29089763e-04   7.84140927e-01  -6.59584883e-01]
 [  1.40209496e+00   6.07960340e-01  -4.31394890e-01  -1.73110573e+00]]


In [4]:
xtrain= xscaled
xtrain=np.insert(xtrain,len(xtrain[0]), values=1, axis=1)
ytrain= train[:,4]

In [5]:
test.shape

(2392, 4)

In [6]:
df= pd.DataFrame(ytrain)

In [7]:

def gGD(m,a,inp,outp):
    mI_slope=np.zeros(len(inp[0]))
    l=len(inp)
    w = len(inp[0])
    for i in range(l):
        var = (-2/l)*(outp[i] - (m*inp[i]).sum())
        for j in range(w):
            mI_slope[j] += var*inp[i][j]
 
    mI_slope= m - a*(mI_slope)
 
    return  mI_slope

In [8]:
def predict(test,m):
    l=len(test)
    y=np.ones(l)
    for i in range(l):
        y[i]=(m[:len(m)-1]*test[i]).sum() + m[len(m)-1]
    
    return y

In [9]:
def cost(m,x,y):
    cost=0
    for i in range(len(x)):
        cost += ((y-  ((m[:len(m)]*x[i]).sum() ))**2)
    avrcost=cost/len(x)
    return avrcost

In [17]:
def run(xtrain,ytrain,a):
    m=np.zeros(len(xtrain[0]))
    iterations=100
    
    for i in range(iterations):
        m=gGD(m,a,xtrain,ytrain)
        print(i)
    
    print(cost(m,xtrain,ytrain))
    return m

In [11]:
def score(ypred,ytrue):
    a= ((ytrue-ypred)**2).sum()
    b= ((ytrue- ytrue.mean())**2).sum()
    return 1- a/b

In [18]:
a=0.15
m=run(xtrain,ytrain,a)


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
[ 1046.11680642   327.79935804   275.18162248 ...,   553.29168569
   302.35715726   371.90587577]


In [19]:
m

array([ -1.45438274e+01,  -3.15991037e+00,   4.16537608e-01,
        -2.22528361e+00,   4.54431293e+02])

In [20]:
y=predict(test,m)
np.savetxt("cpr.csv",y,fmt="%0.5f")