In [1]:
from sklearn import datasets
from sklearn import model_selection 
import numpy as np
from sklearn.neighbors import KNeighborsClassifier

In [2]:
df= datasets.load_iris()

In [3]:
x= df.data
y=df.target

In [4]:
xtrain, xtest,ytrain, ytest=model_selection.train_test_split(x,y,random_state=1)

In [5]:
def fit(xtrain, ytrain):
    return xtrain,ytrain

In [6]:
def probone(x,y,xtest,n):
    arr=[]
    for i in range(len(x)):
            yone= np.sqrt(((x[i,:] - xtest)**2).sum())
            arr.append((yone,y[i]))
    ytest= sorted(arr)
    ans=[]
    for i in range(n):
        ans.append(ytest[i][1])
    return max(ans, key= ans.count)

In [7]:
def prob(xtrain,ytrain,xtest,n):
    res=[]

    for i in range(len(xtest)):
        yone = probone(xtrain,ytrain,xtest[i,:],n)
        res.append(yone)
        
    return res

In [8]:
def predict(xtrain,ytrain,xtest,n):
    yres=prob(xtrain,ytrain,xtest,n)
    return yres

In [41]:
SelfAlgoPred =predict(xtrain,ytrain,xtrain,7)

np.transpose(SelfAlgoPred)

array([1, 2, 2, 0, 2, 2, 1, 2, 0, 0, 0, 1, 0, 0, 2, 2, 2, 2, 2, 1, 2, 1, 0,
       2, 2, 0, 0, 2, 0, 2, 2, 1, 1, 2, 2, 0, 1, 1, 2, 1, 2, 1, 0, 0, 0, 2,
       0, 2, 2, 2, 0, 0, 1, 0, 2, 1, 2, 2, 1, 2, 2, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 2, 2, 2, 0, 0, 2, 0, 2, 0, 2, 1, 0, 2, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 2, 0, 0, 2, 1, 2, 1, 2, 2, 2, 2, 0])

In [36]:
clf=KNeighborsClassifier(n_neighbors=7)


In [38]:
clf.fit(xtrain,ytrain)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=7, p=2,
           weights='uniform')

In [39]:

InbuiltAlgoPred=clf.predict(xtrain)
InbuiltAlgoPred

array([1, 2, 2, 0, 2, 2, 1, 2, 0, 0, 0, 1, 0, 0, 2, 2, 2, 2, 2, 1, 2, 1, 0,
       2, 2, 0, 0, 2, 0, 2, 2, 1, 1, 2, 2, 0, 1, 1, 2, 1, 2, 1, 0, 0, 0, 2,
       0, 2, 2, 2, 0, 0, 1, 0, 2, 1, 2, 2, 1, 2, 2, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 2, 2, 2, 0, 0, 2, 0, 2, 0, 2, 1, 0, 2, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 2, 0, 0, 2, 1, 2, 1, 2, 2, 2, 2, 0])

In [42]:
SelfAlgoPred - InbuiltAlgoPred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])