In [1]:
import numpy as np
import pandas as pd
import sklearn.datasets as Datasets
from sklearn import model_selection

In [2]:
def fit(xtrain,ytrain):
    res_dic={}
    total_classes=set(ytrain)
    res_dic["training_data_count"]= len(ytrain)
    for each_class in total_classes:
        res_dic[each_class]= {}
        data_needed= (each_class==ytrain)
        current_xtrain = xtrain[data_needed]
        current_ytrain = ytrain[data_needed]
        total_features = xtrain.shape[1]
        res_dic[each_class]["total_class_count"]=  data_needed.sum()
        for j in range(1,total_features+1):
            res_dic[each_class][j] = {}
            distinct_class_in_feature = set(xtrain[:,j-1])
            for current_value in  distinct_class_in_feature:
                res_dic[each_class][j][current_value] = (current_xtrain[:,j-1]==current_value).sum()
    return res_dic

In [3]:
def probablity(dic,x,current_class):

    output=np.log(dic[current_class]["total_class_count"]) - np.log(dic["training_data_count"])
    number_of_features= len(dic[current_class].keys()) -1
    for j in range(1,number_of_features+1):
        xj=x[j-1]
        count_of_current_class_with_feature_xj= dic[current_class][j][xj] +1
        count_of_data_in_current_class= dic[current_class]["total_class_count"] + len(dic[current_class][j].keys())
        current_xj_pro= np.log(count_of_current_class_with_feature_xj) -np.log( count_of_data_in_current_class)
        output= output+ current_xj_pro
    return output
        

In [16]:
def predict_one(dic,x):
    best_prob=-1000
    best_class=-1
    a=True
    for current in dic.keys():
    
        if current=="training_data_count":
            continue
        
        prob_for_given_class= probablity(dic,x,current)
        
        if a or prob_for_given_class >best_prob:
        
            best_prob=prob_for_given_class
            best_class= current
            a=False
  
    return best_class

In [5]:
def predict(dic,xtest):
    
    ypred=[]
    for x in xtest:
        y=predict_one(dic,x)
        ypred.append(y)
        
    return ypred


In [6]:
def makeLabelled(column):
    mean = column.mean()
    second_lim= mean
    first_lim= 0.5*mean
    third_lim= 1.5*mean
    
    for i in range (0,len(column)):
        if column[i]< first_lim:
            column[i]=0
        elif column[i]<second_lim:
            column[i]=1
        elif column[i]<third_lim:
            column[i]=2
        else:
            column[i]=3
            
            
    return column

In [7]:
iris = Datasets.load_iris()
df = pd.DataFrame(iris.data)

X = df.values
Y = iris.target

for i in range(0,X.shape[-1]):
    X[:,i] = makeLabelled(X[:,i])

In [8]:
xtrain,xtest,ytrain,ytest=model_selection.train_test_split(X,Y,test_size=0.25,random_state=3
                                                          
                                                          )

In [9]:
dictionary=fit(xtrain,ytrain)
ytrain

array([2, 1, 2, 1, 0, 0, 2, 1, 0, 1, 2, 1, 0, 0, 2, 1, 1, 0, 2, 0, 2, 1, 0,
       0, 2, 1, 0, 0, 1, 2, 2, 0, 2, 1, 0, 0, 2, 2, 2, 1, 1, 1, 0, 0, 2, 2,
       1, 2, 1, 2, 0, 2, 0, 1, 1, 2, 2, 0, 1, 0, 1, 1, 1, 0, 2, 0, 2, 1, 2,
       1, 2, 1, 0, 2, 1, 2, 1, 0, 1, 2, 0, 1, 0, 0, 0, 1, 2, 0, 0, 2, 0, 1,
       2, 1, 2, 2, 1, 1, 2, 1, 0, 1, 1, 0, 1, 2, 2, 2, 0, 0, 2, 2])

In [10]:
type(dictionary["training_data_count"])

int

In [15]:
ypred=predict(dictionary,xtest)

-1.55215896312 -1000
going
-1.55215896312 -1000
going
-1.55215896312 -1000
going
-3.40845695348 -1000
going
-1.55215896312 -1000
going
-14.1026720149 -1000
-8.69983367661 -14.1026720149
-2.73656437996 -8.69983367661
going
-10.5191530765 -1000
-2.5953593726 -10.5191530765
going
-1.55215896312 -1000
going
-14.1026720149 -1000
-5.20332611515 -14.1026720149
-2.39172389366 -5.20332611515
going
-12.2463740246 -1000
-4.04587332646 -12.2463740246
going
-10.5191530765 -1000
-2.5953593726 -10.5191530765
going
-3.40845695348 -1000
going
-10.5191530765 -1000
-2.5953593726 -10.5191530765
going
-10.5191530765 -1000
-2.5953593726 -10.5191530765
going
-12.2463740246 -1000
-6.75392352756 -12.2463740246
-3.04850343005 -6.75392352756
going
-1.55215896312 -1000
going
-14.1026720149 -1000
-2.49527591404 -14.1026720149
going
-14.1026720149 -1000
-8.69983367661 -14.1026720149
-2.73656437996 -8.69983367661
going
-10.5191530765 -1000
-5.3034095737 -10.5191530765
-4.15531248592 -5.3034095737
going
-1.5521589631

In [12]:
from sklearn.metrics import classification_report, confusion_matrix

In [13]:
print(classification_report(ytest,ypred))
print(confusion_matrix(ytest,ypred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        15
          1       0.92      1.00      0.96        12
          2       1.00      0.91      0.95        11

avg / total       0.98      0.97      0.97        38

[[15  0  0]
 [ 0 12  0]
 [ 0  1 10]]
